import { Node, Edge } from '@xyflow/react';
import { BatchNodeData, ActionNodeData, ChoiceQuestion, ScoreQuestion, NoulQuestion } from '../types/workflow';

export function generatePythonCode(nodes: Node[], edges: Edge[]): string {
  const batchNodes = nodes.filter((n: Node) => n.type === 'batchNode');
  const actionNodes = nodes.filter(node => node.type === 'actionNode');

  let code = '# Generated by SysOne GX (TypeSafe Studio)\n' +
    'from typesafe_sdk import TypeSafeClient, Choice, Score, Noul\n' +
    'import json\n\n' +
    'def execute_typesafe_workflow(state_input: str | dict) -> dict:\n' +
    '    """\n' +
    '    Auto-generated decision tree workflow using TypeSafe System One.\n' +
    '    Evaluates batches in parallel and routes through calibrated probabilities.\n' +
    '    """\n' +
    '    results = {}\n' +
    '    with TypeSafeClient() as client:\n';

  batchNodes.forEach((bNode, idx) => {
    const bData = bNode.data as BatchNodeData;
    const stepVar = 'step_' + (idx + 1);
    const questionsVar = 'questions_' + (idx + 1);

    code += '        # --- Step ' + (idx + 1) + ': ' + (bData.title || bNode.id) + ' ---\n';
    code += '        ' + questionsVar + ' = {\n';

    bData.questions.forEach((q) => {
      if (q.type === 'choice') {
        const cq = q as ChoiceQuestion;
        code += '            "' + cq.id + '": Choice(\n' +
          '                instructions=' + JSON.stringify(cq.instructions) + ',\n' +
          '                criteria=' + JSON.stringify(cq.criteria, null, 16).replace(/\n/g, '\n                ') + ',\n' +
          '            ),\n';
      } else if (q.type === 'score') {
        const sq = q as ScoreQuestion;
        code += '            "' + sq.id + '": Score(\n' +
          '                instructions=' + JSON.stringify(sq.instructions) + ',\n' +
          '                criteria=' + JSON.stringify(sq.criteria, null, 16).replace(/\n/g, '\n                ') + ',\n' +
          '            ),\n';
      } else if (q.type === 'noul') {
        const nq = q as NoulQuestion;
        code += '            "' + nq.id + '": Noul(\n' +
          '                instructions=' + JSON.stringify(nq.instructions) + ',\n';
        if (nq.criteria) {
          code += '                criteria=' + JSON.stringify(nq.criteria, null, 16).replace(/\n/g, '\n                ') + ',\n';
        }
        code += '            ),\n';
      }
    });

    code += '        }\n\n';
    code += '        ' + stepVar + ' = client.system_one(\n' +
      '            model="' + (bData.model || 'jev-latest') + '",\n' +
      '            state=state_input,\n' +
      '            questions=' + questionsVar + ',\n' +
      '        )\n';

    code += '        results["' + bNode.id + '"] = ' + stepVar + '.answers\n\n';

    if (bData.enableConfidenceFallback) {
      const fallbackThreshold = bData.confidenceThreshold ?? 0.35;
      const fallbackEdge = edges.find((e) => e.source === bNode.id && e.sourceHandle === 'fallback_handle');
      const targetAction = actionNodes.find((a) => a.id === fallbackEdge?.target);

      code += '        # low confidence guardrail\n' +
        '        for q_id, ans in ' + stepVar + '.answers.items():\n' +
        '            if hasattr(ans, "confidence") and ans.confidence < ' + fallbackThreshold + ':\n' +
        '                return {"action": "' + (targetAction ? (targetAction.data as ActionNodeData).title : 'fallback_action') + '", "reason": "low_confidence"}\n\n';
    }
  });

  code += '        return {"status": "completed", "results": results}\n\n';
  code += 'if __name__ == "__main__":\n' +
    '    sample_ticket = "My shoes arrived in the wrong size. Can I exchange for a size 10?"\n' +
    '    output = execute_typesafe_workflow(sample_ticket)\n' +
    '    print(json.dumps(output, indent=2, default=str))\n';

  return code;
}

export function generateTypeScriptCode(nodes: Node[], _edges: Edge[]): string {
  const batchNodes = nodes.filter(node => node.type === 'batchNode');

  let code = '// Generated by SysOne GX (TypeSafe Studio)\n' +
    'import { TypeSafeClient } from "@typesafe/sdk";\n\n' +
    'export async function executeTypeSafeWorkflow(stateInput: string | Record<string, any>) {\n' +
    '  const allResults: Record<string, any> = {};\n\n';

  batchNodes.forEach((bNode, idx) => {
    const bData = bNode.data as BatchNodeData;
    const questionsObj: Record<string, any> = {};
    bData.questions.forEach((q) => { questionsObj[q.id] = q; });

    code += '  // Step ' + (idx + 1) + ': ' + (bData.title || bNode.id) + '\n' +
      '  const response_' + (idx + 1) + ' = await fetch("https://api.typesafe.ai/v1/systemone", {\n' +
      '    method: "POST",\n' +
      '    headers: { "Content-Type": "application/json", "Authorization": `Bearer ${process.env.TYPESAFE_API_KEY}` },\n' +
      '    body: JSON.stringify({\n' +
      '      model: "' + (bData.model || 'jev-latest') + '",\n' +
      '      state: stateInput,\n' +
      '      questions: ' + JSON.stringify(questionsObj, null, 8).replace(/\n/g, '\n      ') + '\n' +
      '    })\n' +
      '  });\n' +
      '  allResults["' + bNode.id + '"] = await response_' + (idx + 1) + '.json();\n\n';
  });

  code += '  return allResults;\n' +
    '}\n';

  return code;
}